# Imports

In [98]:
import pandas as pd

# Process Data Maltratos (transpose)

In [109]:
# Read 'xlsx' file as pandas dataframe
df = pd.read_excel(r'data/maltratos.xlsx', converters={'Long':str, 'Lat':str}, index_col=None)
# Remove rows based on a column value
df = df.drop(df['Long'].loc[df['Long']=="0"].index)

# Reset index
df.reset_index(drop=True, inplace=True)
# Create new column with index values
df.insert(loc=0, column='Id', value=df.index)

# Create a copy of dataframe and delete columns
df_copy = df.drop(columns=['Long', 'Lat', 'Total', 'Hospital'])

# Add column 'Id' and concatenate str for values
df_copy['Id'] = 'Hospital' + df['Id'].astype(str)
# Set column 'Id' as index
df_copy = df_copy.set_index('Id')

# Transpose dataframe
df_tr = df_copy.transpose()

# Set values for 'Tipos'
tipos = ['Maltrato1', 'Maltrato2', 'Maltrato3', 'Maltrato4', 'Maltrato5', 
         'Maltrato6', 'Maltrato7', 'Maltrato8', 'Maltrato9', 'Maltrato10']
# Add 'Tipos' column
df_tr.insert(loc=0, column='Tipos', value=tipos)

# Set values for 'Maltratos'
maltratos = ['Te llamaron por sobrenombres o diminutivos (mamita, niña, gorda, negra, etc)', 
             'Se burlaron de ti', 
             'Te dijeron que no explícitamente a algo que pediste', 
             'Te hablaron en voz alta de modo grosero', 
             'Ignoraron algo que les pediste', 
             'Te dieron golpes, sacudidas, empujones', 
             'Te dijeron que estabas poniendo en riesgo a tu hijo/a', 
             'Te culparon por situaciones ocurridas en el nacimiento', 
             'Te amenazaron', 
             'Otro tipo de maltrato']
# Add 'Maltratos' column
df_tr.insert(loc=1, column='Maltratos', value=maltratos)

# Save dataframe as 'xlsx'
#df_tr.to_excel(f'data/maltratos_process_copy.xlsx', index = False)
df_tr

Id,Tipos,Maltratos,Hospital0,Hospital1,Hospital2,Hospital3,Hospital4,Hospital5,Hospital6,Hospital7,...,Hospital9,Hospital10,Hospital11,Hospital12,Hospital13,Hospital14,Hospital15,Hospital16,Hospital17,Hospital18
Maltrato1,Maltrato1,Te llamaron por sobrenombres o diminutivos (ma...,1.0,1.0,2.0,19.0,3.0,3.0,1.0,1.0,...,10.0,1.0,2.0,2.0,3.0,3.0,6.0,1.0,2.0,14.0
Maltrato2,Maltrato2,Se burlaron de ti,NaN,NaN,1.0,8.0,2.0,1.0,NaN,1.0,...,4.0,1.0,2.0,1.0,1.0,1.0,3.0,NaN,1.0,4.0
Maltrato3,Maltrato3,Te dijeron que no explícitamente a algo que pe...,NaN,1.0,1.0,22.0,3.0,5.0,NaN,2.0,...,9.0,2.0,2.0,1.0,4.0,1.0,6.0,NaN,1.0,17.0
Maltrato4,Maltrato4,Te hablaron en voz alta de modo grosero,NaN,1.0,1.0,27.0,4.0,6.0,1.0,1.0,...,10.0,2.0,2.0,2.0,5.0,1.0,9.0,1.0,1.0,27.0
Maltrato5,Maltrato5,Ignoraron algo que les pediste,NaN,1.0,1.0,18.0,4.0,5.0,NaN,1.0,...,9.0,2.0,2.0,2.0,4.0,NaN,7.0,1.0,1.0,16.0
Maltrato6,Maltrato6,"Te dieron golpes, sacudidas, empujones",NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,...,NaN,1.0,2.0,1.0,1.0,NaN,1.0,NaN,NaN,1.0
Maltrato7,Maltrato7,Te dijeron que estabas poniendo en riesgo a tu...,NaN,NaN,1.0,16.0,3.0,1.0,NaN,1.0,...,3.0,2.0,2.0,2.0,2.0,NaN,3.0,2.0,1.0,12.0
Maltrato8,Maltrato8,Te culparon por situaciones ocurridas en el na...,NaN,NaN,NaN,3.0,NaN,NaN,NaN,1.0,...,2.0,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,3.0
Maltrato9,Maltrato9,Te amenazaron,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,...,1.0,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN,3.0
Maltrato10,Maltrato10,Otro tipo de maltrato,1.0,1.0,NaN,17.0,1.0,NaN,1.0,1.0,...,2.0,1.0,1.0,2.0,5.0,NaN,4.0,NaN,2.0,18.0

# Process Data Consentimiento

In [110]:
# Read 'xlsx' file as pandas dataframe
df1 = pd.read_excel(r'data/desagregada/no.xlsx', index_col=None)
df2 = pd.read_excel(r'data/desagregada/algunos.xlsx', index_col=None)
df3 = pd.read_excel(r'data/desagregada/todos.xlsx', index_col=None)

# Remove '\n' from column 'Hospital'
df1['Hospital'].replace(r'\n|^\s', '', regex=True, inplace=True)
df2['Hospital'].replace(r'\n|^\s', '', regex=True, inplace=True)
df3['Hospital'].replace(r'\n|^\s', '', regex=True, inplace=True)

# Remove rows based on a column value
df1 = df1.dropna(subset=['Hospital'])
df2 = df2.dropna(subset=['Hospital'])
df3 = df3.dropna(subset=['Hospital'])
# Remove rows by index value
df1 = df1.drop(df1.index[11])
# Remove first row with atypical value
df3 = df3.iloc[1: , :]

# Merge dataframes by a column
df_join = pd.merge(df1, df2, on ='Hospital', how ='left')
df_join = pd.merge(df_join, df3, on ='Hospital', how ='left')

# Read 'xlsx' file as pandas dataframe
df4 = pd.read_excel(r'data/maltratos.xlsx', index_col=None)

# Create a copy of columns to new df
new = df4[['Hospital', 'Long', 'Lat']].copy()
df_final = pd.merge(df_join, new, on ='Hospital', how ='left')

# Copy columns and remove from df
long = df_final.pop('Long')
lat = df_final.pop('Lat')
# Insert columns in new order
df_final.insert(1, "Long", long)
df_final.insert(2, "Lat", lat)

# Save dataframe as 'xlsx'
#df_final.to_excel('data/consent_copy.xlsx', index = False)

df_final

,Hospital,Long,Lat,Count_No,Count_Algunos,Count_Todos
0,Hospital Guillermo Domínguez (Puerto Padre),NaN,NaN,1,NaN,1.0
1,Hospital General Docente 26 de Diciembre de R...,NaN,NaN,1,NaN,NaN
2,Hospital General Docente Vladimir Ilich Lenin,20.888218,-76.269230,2,NaN,NaN
3,Hospital Ginecobstétrico Ramón González Coro,23.130922,-82.397801,40,6.0,30.0
4,Hospital Materno Infantil provincial Isabel Ma...,0.000000,0.000000,2,NaN,1.0
5,Hospital Militar Luis Díaz Soto (Naval),0.000000,0.000000,2,1.0,5.0
6,Hospital Pediátrico Provincial Docente Pepé Po...,NaN,NaN,1,NaN,NaN
7,Hospital Provincial Universitario Camilo Cienf...,NaN,NaN,1,NaN,2.0
8,Hospital Universitario Abel Santamaría Cuadrado,22.440424,-83.671156,8,NaN,27.0
9,Hospital Universitario Ginecobstétrico Mariana...,22.390862,-79.954159,7,NaN,13.0
10,El Hospital General Universitario Dr. Gustavo ...,NaN,NaN,2,NaN,NaN
11,Hospital Clínico Quirúrgico Amalia Simoni,21.404316,-77.887804,1,NaN,NaN
12,Hospital Docente Ginecobstétrico de Guanabacoa...,23.129327,-82.304263,5,1.0,3.0
13,Hospital General Docente Dr. Antonio Luaces Ir...,NaN,NaN,1,NaN,1.0
14,Hospital General Docente Enrique Cabrera (Naci...,23.060262,-82.391809,13,NaN,5.0
15,Hospital General Docente Héroes de Baire,21.891307,-82.806549,1,1.0,2.0
16,Hospital General Docente Iván Portuondo,22.893242,-82.505021,3,NaN,1.0
17,Hospital General Docente Julio Aristegui Villamil,0.000000,0.000000,4,3.0,3.0
18,Hospital General Docente Leopoldito Martínez,NaN,NaN,1,NaN,NaN
19,Hospital General Docente Universitario Martin ...,21.535902,-77.274460,3,NaN,NaN
20,Hospital Ginecobstétrico América Arias (Matern...,23.142519,-82.392210,13,1.0,12.0
21,Hospital Ginecobstétrico Clodomira Acosta,23.130239,-82.400438,4,NaN,1.0
22,Hospital Ginecobstétrico Docente Dra. Nelia I....,NaN,NaN,1,1.0,NaN
23,Hospital Ginecobstétrico Provincial Ana Betanc...,0.000000,0.000000,31,3.0,31.0
24,Hospital Materno Hijas de Galicia (Hospital Ma...,23.104871,-82.357849,13,3.0,13.0
25,Hospital Materno Infantil Dr. Ángel Arturo Aballí,23.055444,-82.366452,3,2.0,2.0
26,Hospital Materno Infantil Lebredo,0.000000,0.000000,3,NaN,NaN
27,Hospital Materno Infantil Manuel Piti Fajardo,22.859900,-82.032284,2,NaN,NaN
28,Hospital Materno Norte Tamara Bunke,NaN,NaN,2,NaN,NaN
29,Hospital Materno Sur (Clínica Los Ángeles),0.000000,0.000000,1,NaN,2.0
30,Hospital Provincial Ginecobstétrico Julio Rafa...,NaN,NaN,1,NaN,8.0
31,Hospital Rural Isidro de Armas,NaN,NaN,1,NaN,NaN
32,Hospital Universitario Ginecobstétrico Eusebio...,23.069793,-82.421092,57,10.0,53.0

# Process Data Consentimiento (transpose)

In [115]:
# Create a copy of df
df_new = df_final.copy()

# Reset index
df_new.reset_index(drop=True, inplace=True)
# Create new column with index values
df_new.insert(loc=0, column='Id', value=df_new.index)

# Create a copy of dataframe and delete columns
df_new = df_new.drop(columns=['Hospital', 'Long', 'Lat'])

# Modify column 'Id' and concatenate str for values
df_new['Id'] = 'Hospital' + df_new['Id'].astype(str)

# Set column 'Id' as index
df_new = df_new.set_index('Id')

# Transpose dataframe
df_tr2 = df_new.transpose()

# Save dataframe as 'xlsx'
#df_tr2.to_excel('data/consent_process_copy.xlsx', index = False)

df_tr2

Id,Hospital0,Hospital1,Hospital2,Hospital3,Hospital4,Hospital5,Hospital6,Hospital7,Hospital8,Hospital9,...,Hospital23,Hospital24,Hospital25,Hospital26,Hospital27,Hospital28,Hospital29,Hospital30,Hospital31,Hospital32
Count_No,1.0,1.0,2.0,40.0,2.0,2.0,1.0,1.0,8.0,7.0,...,31.0,13.0,3.0,3.0,2.0,2.0,1.0,1.0,1.0,57.0
Count_Algunos,NaN,NaN,NaN,6.0,NaN,1.0,NaN,NaN,NaN,NaN,...,3.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,10.0
Count_Todos,1.0,NaN,NaN,30.0,1.0,5.0,NaN,2.0,27.0,13.0,...,31.0,13.0,2.0,NaN,NaN,NaN,2.0,8.0,NaN,53.0