# Imports

In [6]:
import pandas as pd

# Process Data

In [7]:
# Read 'xlsx' file as pandas dataframe
df = pd.read_excel(r'data/hospitales.xlsx', converters={'Long':str, 'Lat':str}, index_col=None)
# Remove rows based on a column value
df = df.drop(df['Long'].loc[df['Long']=="0"].index)

# Reset index
df.reset_index(drop=True, inplace=True)
# Create new column with index values
df.insert(loc=0, column='Id', value=df.index)

# Create a copy of dataframe and delete columns
df_copy = df.drop(columns=['Long', 'Lat', 'Total', 'Hospital'])

# Add column 'Id' and concatenate str for values
df_copy['Id'] = 'Hospital' + df['Id'].astype(str)
# Set column 'Id' as index
df_copy = df_copy.set_index('Id')

# Transpose dataframe
df_tr = df_copy.transpose()

# Set values for 'Tipos'
tipos = ['Maltrato1', 'Maltrato2', 'Maltrato3', 'Maltrato4', 'Maltrato5', 
         'Maltrato6', 'Maltrato7', 'Maltrato8', 'Maltrato9', 'Maltrato10']
# Add 'Tipos' column
df_tr.insert(loc=0, column='Tipos', value=tipos)

# Set values for 'Maltratos'
maltratos = ['Te llamaron por sobrenombres o diminutivos (mamita, niña, gorda, negra, etc)', 
             'Se burlaron de ti', 
             'Te dijeron que no explícitamente a algo que pediste', 
             'Te hablaron en voz alta de modo grosero', 
             'Ignoraron algo que les pediste', 
             'Te dieron golpes, sacudidas, empujones', 
             'Te dijeron que estabas poniendo en riesgo a tu hijo/a', 
             'Te culparon por situaciones ocurridas en el nacimiento', 
             'Te amenazaron', 
             'Otro tipo de maltrato']
# Add 'Maltratos' column
df_tr.insert(loc=1, column='Maltratos', value=maltratos)

# Save dataframe as 'xlsx'
#df_tr.to_excel(f'data/hospitales_process.xlsx', index = False)
df_tr

Id,Tipos,Maltratos,Hospital0,Hospital1,Hospital2,Hospital3,Hospital4,Hospital5,Hospital6,Hospital7,...,Hospital9,Hospital10,Hospital11,Hospital12,Hospital13,Hospital14,Hospital15,Hospital16,Hospital17,Hospital18
Maltrato1,Maltrato1,Te llamaron por sobrenombres o diminutivos (ma...,1.0,1.0,2.0,19.0,3.0,3.0,1.0,1.0,...,10.0,1.0,2.0,2.0,3.0,3.0,6.0,1.0,2.0,14.0
Maltrato2,Maltrato2,Se burlaron de ti,NaN,NaN,1.0,8.0,2.0,1.0,NaN,1.0,...,4.0,1.0,2.0,1.0,1.0,1.0,3.0,NaN,1.0,4.0
Maltrato3,Maltrato3,Te dijeron que no explícitamente a algo que pe...,NaN,1.0,1.0,22.0,3.0,5.0,NaN,2.0,...,9.0,2.0,2.0,1.0,4.0,1.0,6.0,NaN,1.0,17.0
Maltrato4,Maltrato4,Te hablaron en voz alta de modo grosero,NaN,1.0,1.0,27.0,4.0,6.0,1.0,1.0,...,10.0,2.0,2.0,2.0,5.0,1.0,9.0,1.0,1.0,27.0
Maltrato5,Maltrato5,Ignoraron algo que les pediste,NaN,1.0,1.0,18.0,4.0,5.0,NaN,1.0,...,9.0,2.0,2.0,2.0,4.0,NaN,7.0,1.0,1.0,16.0
Maltrato6,Maltrato6,"Te dieron golpes, sacudidas, empujones",NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,...,NaN,1.0,2.0,1.0,1.0,NaN,1.0,NaN,NaN,1.0
Maltrato7,Maltrato7,Te dijeron que estabas poniendo en riesgo a tu...,NaN,NaN,1.0,16.0,3.0,1.0,NaN,1.0,...,3.0,2.0,2.0,2.0,2.0,NaN,3.0,2.0,1.0,12.0
Maltrato8,Maltrato8,Te culparon por situaciones ocurridas en el na...,NaN,NaN,NaN,3.0,NaN,NaN,NaN,1.0,...,2.0,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,3.0
Maltrato9,Maltrato9,Te amenazaron,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,...,1.0,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN,3.0
Maltrato10,Maltrato10,Otro tipo de maltrato,1.0,1.0,NaN,17.0,1.0,NaN,1.0,1.0,...,2.0,1.0,1.0,2.0,5.0,NaN,4.0,NaN,2.0,18.0